version: "3.5"
services:
  https.dnp.dappnode.eth:
    build: .
    container_name: DAppNodeCore-https.dnp.dappnode.eth
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      CERTAPI_URL: "ns.dappnode.io:5000"
      LOCAL_PROXYING: "true"
      WEBSOCKET: "true"
      MAPPING_EXTERNAL_BY_DEFAULT: "true"
      FORCE: null
      PRIVATE_SUBNET: null
      CLIENT_MAX_BODY_SIZE: null
      PROXY_BUFFERING: null
    networks:
      dncore_network:
        aliases:
          - https.dappnode
    volumes:
      - "portal-certs:/etc/ssl/dappnode"
      - "portal-data:/usr/src/app/domains"
volumes:
  portal-certs: {}
  portal-data: {}
networks:
  dncore_network:
    name: dncore_network
    external: true
